# NAME: Bonnie Liu,Janice Tsai
# EMAIL: bonnieliu2002@g.ucla.edu,janicetsai@g.ucla.edu
# ID: 005300989,705318599

default: lab3a.c
	gcc -Wall -Wextra -o lab3a lab3a.c

dist: default
	tar -cvzf lab3a-705318599.tar.gz lab3a.c README Makefile ext2_fs.h

clean:
	rm -f lab3a lab3a-705318599.tar.gz
